name: check
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: "^22"
      - run: yarn install --frozen-lockfile
      - run: yarn test --coverage
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: "^22"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: "^22"
      - run: yarn install --frozen-lockfile
      - run: yarn build --noEmit
  lint-docs:
    defaults:
      run:
        working-directory: ./docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: "^22"
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  build-docs:
    defaults:
      run:
        working-directory: ./docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: "^22"
      - run: cd .. && yarn install --frozen-lockfile && yarn build
      - run: yarn install --frozen-lockfile
      - run: yarn build
